# Pytorch
* pytorch의 tensor를 통해 3차원 배열 이상의 고차원 데이터를 다룸. - Numpy 배열과 매우 유사
* GPU 연동을 통한 딥러닝 모델 학습 가능

In [3]:
import torch

device = torch.device('mps')
print(f'device : {device}')

# 일반적인 Nvidia GPU를 활용할 경우에는 GPU 가속화를 위해 cuda에 할당하지만
# Apple M1 에서는 Metal(MPS)으로 변경하여 사용해야 한다.

device : mps


## 1. GPU 사용 여부 체크
* tensor 간 연산을 수행할 때 기본적으로 같은 장치에 있어야 함. 둘다 CPU에 있거나 GPU에 있어야 함.
* 가능하면 연산을 수행하는 모든 텐서를 GPU에 올린 후 연산을 수행 -> 보다 더 시간적으로 효율적
* 딥러닝 모델에 넣는 데이터는 기본적으로 tensor 형태임

In [9]:
import torch
data = [
    [1,2],
    [3,4],
]

x = torch.tensor(data)
print(x.is_mps)

x = x.to(device) # move to GPU
print(x.is_mps)

x = x.cpu() # move to CPU
print(x.is_mps)

False
True
False


* 서로 다른 device에 있는 tensor간의 연산은 수행할 수 없음 -> 오류 발생

In [4]:
# tensor on GPU
a = torch.tensor([
    [1,1],
    [2,2]
]).to(device)

# tensor on CPU
b = torch.tensor([
    [5,6],
    [7,8]
])

print(torch.matmul(a,b))

RuntimeError: MPS device does not support mm for non-float inputs

In [7]:
print(torch.matmul(a.cpu(), b))

tensor([[12, 14],
        [24, 28]])


## 2. Tensor 기능
* tensor는 기본적으로 다차원 배열을 처리하기에 적합한 자료구조이다.
* 딥러닝 모델을 학습하고 데이터를 불러올 때 데이터를 처리하기 적합하다.
* 자동 미분 기능을 제공한다.

### 2-1. 텐서 속성
* 텐서의 기본 속성은 다음과 같다
  * 모양(shape)
  * 자료형(data type)
  * 저장된 장치

In [8]:
tensor = torch.rand(4,5)

print(tensor)

# tensor의 크기를 확인할 수 있음 4 * 5 tensor 행렬
print(f'tensor shape : {tensor.shape}') 

# tensor의 자료형을 확인할 수 있음 float32
print(f'tensor data type : {tensor.dtype}')

# tensor의 장치를 확인할 수 있음 cpu
print(f'tensor device : {tensor.device}')

tensor([[0.4852, 0.0151, 0.2299, 0.9312, 0.3023],
        [0.4836, 0.2959, 0.1317, 0.3078, 0.2587],
        [0.3409, 0.5179, 0.9627, 0.4827, 0.5240],
        [0.1211, 0.9758, 0.1691, 0.9993, 0.7896]])
tensor shape : torch.Size([4, 5])
tensor data type : torch.float32
tensor device : cpu


### 2-2. 텐서 초기화
* 리스트 데이터에서 직접 tensor를 초기화 할 수 있다.

In [9]:
data = [
    [2, 5],
    [3, 7],
]

x = torch.tensor(data)

print(x)

tensor([[2, 5],
        [3, 7]])


* Numpy 배열에서 tensor를 초기화하는 것도 가능하다.

In [13]:
a = torch.tensor([3])
b = torch.tensor([2])

c = (a+b).numpy()
print(c)
print(type(c))

res = c * 10
tensor = torch.from_numpy(res)
print(tensor)
print(type(tensor))

# numpy()를 통해서 numpy 배열로 변환할 할 수 있고, 반대로 from_numpy()를 통해서 tensor로 변환할 수 있다.

[5]
<class 'numpy.ndarray'>
tensor([50])
<class 'torch.Tensor'>


### 2-3. 다른 텐서로부터 텐서 초기화하기
* 다른 텐서의 정보를 토대로 텐서를 초기화할 수 있다.
* 텐서의 속성 : 모양(shape), 자료형 (data type)


In [15]:
x = torch.tensor([
    [9, 2],
    [5, 3]
])

# x와 같은 shape와 자료형을 가지지만, 모든 원소가 1인 텐서 생성
x_ones = torch.ones_like(x)
print(f"Ones Tensor: \n {x_ones} \n")

# x와 같은 shape와 자료형을 가지지만, 자료형은 float32이고, 값은 랜덤인 텐서 생성
x_rand = torch.rand_like(x, dtype=torch.float32)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9919, 0.9293],
        [0.9922, 0.7243]]) 

