In [2]:
import torch
device = torch.device('mps')

# 일반적인 Nvidia GPU를 활용할 경우에는 GPU 가속화를 위해 cuda에 할당하지만
# Apple M1 에서는 Metal(MPS)으로 변경하여 사용해야 한다.

device : mps


# 3. 텐서의 형변환 및 차원 조작
* 고차원의 데이터를 처리하는데 있어서 텐서를 활용하는 것이 용이하다
* 텐서는 Numpy 배열처럼 조작할수 있다

## 3-1. 텐서의 특정 차원 접근하기
* 텐서는 원하는 차원에 접근할 수 있다
* 파이썬에서 사용하는 indexing 기법이나 slicing 기법 등을 사용하여 간단하게 접근할 수 있다.

In [3]:
tensor = torch.tensor([
    [4,5,6,7],
    [1,3,2,8],
    [11,13,15,17]
])

# print first row
print(tensor[0])
# print first column
print(tensor[:,0])
# print last column
print(tensor[:,-1])

tensor([4, 5, 6, 7])
tensor([ 4,  1, 11])
tensor([ 7,  8, 17])


## 3-2. 텐서 이어 붙이기 (concatenate)
* 두 개의 텐서를 이어 붙여 연결해서 새로운 텐서룰 생성할 수 있다.
* dim, axis : 텐서를 이어 붙이기 위한 축
* 0일 경우 행을 의미하고, 1일 경우 열을 의미한다.

In [6]:
tensor = torch.tensor([
    [6,3,2,7],
    [1,5,4,8],
    [2,7,6,9],
])

# dim = 0 : 0번 축(행) 을 기준으로 
res = torch.cat([tensor, tensor], dim=0)
print(res)

# dim = 1 : 1번 축(열) 을 기준으로
res = torch.cat([tensor, tensor], dim=1)
print(res)

# axis = 0 : 0번 축(행) 을 기준으로
res = torch.cat([tensor, tensor], axis=0)
print(res)

# axis = 1 : 1번 축(열) 을 기준으로
res = torch.cat([tensor, tensor], axis=1)
print(res)

tensor([[6, 3, 2, 7],
        [1, 5, 4, 8],
        [2, 7, 6, 9],
        [6, 3, 2, 7],
        [1, 5, 4, 8],
        [2, 7, 6, 9]])
tensor([[6, 3, 2, 7, 6, 3, 2, 7],
        [1, 5, 4, 8, 1, 5, 4, 8],
        [2, 7, 6, 9, 2, 7, 6, 9]])
tensor([[6, 3, 2, 7],
        [1, 5, 4, 8],
        [2, 7, 6, 9],
        [6, 3, 2, 7],
        [1, 5, 4, 8],
        [2, 7, 6, 9]])
tensor([[6, 3, 2, 7, 6, 3, 2, 7],
        [1, 5, 4, 8, 1, 5, 4, 8],
        [2, 7, 6, 9, 2, 7, 6, 9]])


## 3-3. 텐서 형변환(type casting)
* torch안에 정의된 데이터 타입을 명시하여 텐서의 자료형을 변환할 수 있다
* 일반적인 파이썬과 마찬가지로 실수와 정수간의 연산을 수행할 때 실수형으로 자동으로 변환하여 처리한다.

In [4]:
a = torch.tensor([3], dtype=torch.int)
b = torch.tensor([6.0])

print(a.dtype)
print(b.dtype)

# 실수 데이터 타입 텐서와 정수 데이터 타입의 텐서를 연산을 수행하면 정수 데이터 타입을 자동으로 float32형으로 형변환
print(a + b)
# 실수 데이터 타입 텐서를 int로 형 변환하여 덧셈 연산 수행
print(a + b.int())
print(a + b.type(torch.int))

torch.int32
torch.float32
tensor([9.])
tensor([9], dtype=torch.int32)
tensor([9], dtype=torch.int32)


## 3-4. 텐서의 모양 변경
* view 메서드는 텐서의 모양(shape)를 변경할 때 사용
* 이떄 텐서의 순서는 변경되지 않음

In [9]:
# view()를 통해 텐서의 모양을 변경할 수 있으나 순서는 변경되지 않는다.
# 따라서 순서가 바뀌면 오류가 발생한다.
# 해당 텐서의 메모리 주소를 참조하기 때문에 참조하는 텐서를 변경하면 같이 변경된다
a = torch.tensor([4,6,2,5,9,1,3,7])
b = a.view(4,2)
print(b)

# a를 변경하면 b도 변경된다
a[0] = 10
print(b)

# a를 복사하고 변경한다 -> 참조하는 텐서가 바뀌어도 영향을 받지 않음
c = a.clone().view(4,2)
a[0] = 20
print(c)

tensor([[4, 6],
        [2, 5],
        [9, 1],
        [3, 7]])
tensor([[10,  6],
        [ 2,  5],
        [ 9,  1],
        [ 3,  7]])
tensor([[10,  6],
        [ 2,  5],
        [ 9,  1],
        [ 3,  7]])


## 3-5. 텐서의 차원 교환
* 하나의 텐서에서 특정한 차원끼리 순서를 교체할 수 있다. - permute

In [13]:
# torch.rand는 정규 분포에서 무작위로 추출한 난수를 가지고 지정된 크기의 텐서를 생성한다.
a = torch.rand([64, 32, 3]) # 64x32x3 텐서 생성
print(a.shape)

b = a.permute(2, 1, 0) # 차원자체를  변경 (2번째 축, 1번째 축, 0번쨰 축)의 형태가 되도록 한다)
print(b.shape)

torch.Size([64, 32, 3])
torch.Size([3, 32, 64])
