In [1]:
import torch

device = torch.device('mps')

# 4. 텐서의 연산과 함수

## 4-1. 텐서의 연산
* 텐서에 대하여 사칙 연산 등 기본적인 연산을 수행할 수 있다.

In [2]:
# 같은 크기를 가진 2개의 텐서에 대한 사칙연산 가능
# 기본적으로 요소별 연산을 진행함

a = torch.tensor([
    [1,2],
    [3,4]
])

b = torch.tensor([
    [7,8],
    [9,10]
])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
# 연산 시 요소별 연산 수행

tensor([[ 8, 10],
        [12, 14]])
tensor([[-6, -6],
        [-6, -6]])
tensor([[ 7, 16],
        [27, 40]])
tensor([[0.1429, 0.2500],
        [0.3333, 0.4000]])


* 또한 tensor 행렬 간 곱을 수행할 수도 있다.
* 행렬 곱은 딥러닝 분야에서 매우 많이 수행된다.
* 따라서 이에 대한 분명한 이해가 필요하다.

In [3]:
# 행렬 간의 곱 수행 
# 행렬 곱 연산 순서는 다음과 같다
# 두 행렬 a의 열 개수와 행렬 b의 행 개수가 같아야 한다
# 행렬 a의 제 i행의 각 성분과 행렬 b의 각 j열의 각 성분을 순서대로 곱하여 더한 것을 
# (i,j) 성분으로 하는 행렬을 두 행렬 a와 b의 곱이라 한다.

a = torch.tensor([
    [5,4],
    [3,2]
])

b = torch.tensor([
    [6,8],
    [7,5]
])


print(a.matmul(b)) 
print(torch.mm(a,b))
print(torch.matmul(a,b))

tensor([[58, 60],
        [32, 34]])
tensor([[58, 60],
        [32, 34]])
tensor([[58, 60],
        [32, 34]])


## 4-2. 텐서의 평균 함수
* 텐서의 평균을 계산할 수 있다 - mean

In [13]:
a = torch.tensor([
    [3,2,1,4],
    [7,5,6,8],
])

print(a)
print(a.mean(dtype=torch.float32)) # 평균
print(a.mean(dim=0, dtype=torch.float32)) # 열 기준 평균 (세로)
print(a.mean(dim=1, dtype=torch.float32)) # 행 기준 평균 (가로)

tensor([[3, 2, 1, 4],
        [7, 5, 6, 8]])
tensor(4.5000)
tensor([5.0000, 3.5000, 3.5000, 6.0000])
tensor([2.5000, 6.5000])


In [16]:
a = torch.tensor([
    [3,2,1,4],
    [1,2,3,4],
])

print(a)
print(a.sum()) # 전체 합
print(a.sum(dim=0)) # 열 합
print(a.sum(dim=1)) # 행 합

tensor([[3, 2, 1, 4],
        [1, 2, 3, 4]])
tensor(20)
tensor([4, 4, 4, 8])
tensor([10, 10])


## 4-4. 텐서의 최대 함수
* max() 함수는 원소의 최댓값을 반환한다.
* argmax() 함수는 가장 큰 원소(최댓값)의 인덱스를 반환한다.
* indices를 보면 열(dim=0)이나 행(dim=1)기준으로 어떤 인덱스에서 최댓값이 위치하는지 확인할 수 있다.

In [17]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(a)
print(a.max()) # 전체 원소의 최댓값
print(a.max(dim=0)) # 각 열의 최댓값 
print(a.max(dim=1)) # 각 행의 최댓값

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor(6)
torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))


In [18]:
a = torch.tensor([
    [4,1,2,3],
    [6,8,5,7]
])

print(a.argmax()) # 최대값의 인덱스
print(a.argmax(dim=0)) # 열 단위로 최대값의 인덱스
# 4,6 중에 6이 크고 (세로 기준 1번째 인덱스), 1,8 중에 8이 크고 (세로 기준 1번째 인덱스) ...
print(a.argmax(dim=1)) # 행 단위로 최대값의 인덱스
# 4,1,2,3 중에 4가 크고 (가로 기준 0번째 인덱스), 6,8,5,7 중에 8이 크고 (세로 기준 1번째 인덱스)

tensor(5)
tensor([1, 1, 1, 1])
tensor([0, 1])


## 4-5. 텐서의 차원 줄이기 혹은 늘리기
* squeeze() 함수는 크기가 1인 차원을 제거해 준다.
    * 주의할 점은 batch가 1일 때 batch차원도 제거하는 경우가 발생함
    * validation 단계에서 오류가 발생할 수 있으므로 주의해서 사용
* unsqueeze() 함수는 크기가 1인 차원을 추가하는 함수이다.
    * batch 차원을 추가하기 위한 목적으로 사용한다.

In [24]:
a = torch.tensor([
    [4,1,2,3],
    [6,8,5,7]
])

print(a.shape) # 2 * 4 행렬

# 첫 번째 축에 차원 추가
a = a.unsqueeze(0)
print(a)
print(a.shape) # 1 * 2 * 4 행렬

# 네 번째 축에 차원 추가
a = a.unsqueeze(3)
print(a)
print(a.shape) # 1 * 2 * 4 * 1 행렬


torch.Size([2, 4])
tensor([[[4, 1, 2, 3],
         [6, 8, 5, 7]]])
torch.Size([1, 2, 4])
tensor([[[[4],
          [1],
          [2],
          [3]],

         [[6],
          [8],
          [5],
          [7]]]])
torch.Size([1, 2, 4, 1])


코드 추가 설명 - tensor 차원의 개념

- 원래 a 행렬은 2x4 행렬이다.

```
[
  [4, 1, 2, 3],
  [6, 8, 5, 7]
]
```

- .unsqueeze(0)를 호출하면, 이 행렬은 3차원 텐서로 변환되며, 새로운 차원은 다른 모든 차원의 "상자" 또는 "컨테이너" 역할을 한다. 새로운 텐서는 다음과 같이 보인다.

```
[
  [
    [4, 1, 2, 3],
    [6, 8, 5, 7]
  ]
]
```

- 이제 이 텐서는 1x2x4 텐서다. 1은 새로운 차원의 크기이다. 여기에는 단 하나의 원소 - 원래의 2x4 행렬만 존재한다.

```
원래 행렬:
2D (2x4)
+---+---+---+---+
| 4 | 1 | 2 | 3 |
+---+---+---+---+
| 6 | 8 | 5 | 7 |
+---+---+---+---+

.unsqueeze(0) 후:
3D (1x2x4)
+---------------+
| +---+---+---+---+ |
| | 4 | 1 | 2 | 3 | |
| +---+---+---+---+ |
| | 6 | 8 | 5 | 7 | |
| +---+---+---+---+ |
+---------------+
```

- .unsqueeze(3)을 호출하면 각 요소가 하나의 배열로 감싸지면서 1x2x4x1 배열이 된다.

```
[
  [
    [[4], [1], [2], [3]],
    [[6], [8], [5], [7]]
  ]
]
```

```
.unsqueeze(3) 후:
4D (1x2x4x1)
+---------------------------------+
| +---------+         +---------+ |
| | +---+   |         | +---+   | |
| | | 4 |   |         | | 6 |   | |
| | +---+   |         | +---+   | |
| | +---+   |         | +---+   | |
| | | 1 |   |         | | 8 |   | |
| | +---+   |         | +---+   | |
| | +---+   |         | +---+   | |
| | | 2 |   |         | | 5 |   | |
| | +---+   |         | +---+   | |
| | +---+   |         | +---+   | |
| | | 3 |   |         | | 7 |   | |
| | +---+   |         | +---+   | |
| +---------+         +---------+ |
+---------------------------------+
```
